schema_version: 1

context:
  name: module-qc-tools
  version: "2.7.0"
  python_min: '3.9'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/module_qc_tools-${{ version }}.tar.gz
  sha256: 8b21b37bdecd7e3ae92fc80c15b94f817082740b4328cfa93de9ce145123606a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - module-qc-tools = module_qc_tools.cli:app
      - mqt = module_qc_tools.cli:app

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=0.7
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - numpy
    - tabulate
    - pre-commit
    - check-jsonschema
    - module-qc-data-tools >=1.3.0
    - module-qc-database-tools >=2.7.0
    - requests
    - typer >=0.9.0
    - rich
    - packaging

tests:
  - python:
      imports:
        - module_qc_tools
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - mqt --help
      - mqt --version
      - module-qc-tools --help
      - module-qc-tools --version

about:
  summary: Module qc tools
  homepage: https://gitlab.cern.ch/atlas-itk/pixel/module/module-qc-tools
  repository: https://gitlab.cern.ch/atlas-itk/pixel/module/module-qc-tools
  documentation: https://atlas-itk-pixel-mqt.docs.cern.ch/latest/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kratsg
    - elisabettapianori
    - marijamarjanovic
    - lime86
